version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:2.430-jdk21
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - "8080:8080"
    volumes:
      - "/home/altug/Desktop/jenkinsContainer/jenkins_home:/var/jenkins_home"